### PR TITLE
[WIP] refactor: migrate to wmr

### PR DESCRIPTION
**Pull request by mutoe**
I am replacing webpack with wmr, temporarily removing the test, and later I will use testing-library to replace enzyme

### CODE REVIEW

**Comment by rschristian** [comment]
There's a few things that need to be waited on from wmr and preact-iso

Edit: Also was trying to get a bit more step-by-step, keep things a bit more sane & reviewable that way. I'd say let's hold off on swapping WMR in, I think that's actually one of the items that can come last. Few things I want to target first.

**Comment by mutoe** [comment]
> There's a few things that need to be waited on from wmr and preact-iso
> 
> Edit: Also was trying to get a bit more step-by-step, keep things a bit more sane & reviewable that way. I'd say let's hold off on swapping WMR in, I think that's actually one of the items that can come last. Few things I want to target first.

What's worse? I think it seems to be available

**Comment by rschristian** [comment]
There's some things that have yet to be released / PR'd that are planned

**Comment by mutoe** [comment]
OK, If you have any ideas, you can put them forward at any time.

**Comment by rschristian** [comment]
I sort of finished up my planning earlier this evening, was going to go through and start the gradual PRs. After the one I've already set, I want to then hit directory structure, codestyle, state probably, the API requests, then I think WMR / Preact-ISO. Get the smaller stuff out of the way first while we wait for them, anyhow.

**Pull request closed without merging**
