### PR TITLE
refactor: Requests and State Management

### PR DESCRIPTION
**Pull request by rschristian**
No where near ready, but to give you an idea of what I'm doing. Swapping out the home grown stuff for some solid (?) externals. 

Never used Zustand before, but [it's quite light](https://bundlephobia.com/result?p=zustand@3.3.3), which  works well with Preact, and has a decent API. Nothing against what you've written, it clearly works well, but I think externalizing that to something that's proven is probably a decent move. Most users do end up externalizing in some way anyways.

The requests I'm tentatively swapping out with `ts-api-toolkit`. It is my own lib, and I might still rip it out, but seems like a decent fit. It's a thin wrapper around [redaxios](http://github.com/developit/redaxios), a [super-light wrapper](https://bundlephobia.com/result?p=redaxios@0.4.1) around the Fetch API that provides the (much loved) Axios API. The API toolkit combines this wrapper with some automated JWT handling, so there doesn't need to be any writing/reading from localStorage for tokens. It'll handle it. Seemed like a decent fit, but like I say, I might end up removing it as it is my tool and quite niche. The downloads per week on it certainly aren't impressive, lol.

Both of these should end up saving some bytes, as well as externalize some of the work. 

Slowly fixing up the pages one by one as I go, mostly just inconsistencies, though there are a few logic gaps here and there.

### CODE REVIEW

**Comment by mutoe** [comment]
Sounds cool,  I also like the small code, initially, 3kb attracted me to use Preact. XD

**Comment by rschristian** [comment]
This is quickly becoming un-reviewable as I keep fixing up small, unrelated items, so I'm going to break them out & rebase this, try to keep it targeted as best as I can.

**Comment by rschristian** [comment]
Think this is ready. Figuring out the test suite is going to be another PR, as that'll be quite a few edits too I imagine.

**Review by mutoe — APPROVED** [review]

**Comment by rschristian** [comment]
Merging this in. I think there's still some items to touch up here and there, but once this + the wmr stuff is out of the way, it'll be a lot easier to just touch up small portions. 

Zustand is getting a pure ESM release soon here (I hope) which should cut down the bundle a little bit too.

**Pull request merged**
