### PR TITLE
Refactor/wmr

### PR DESCRIPTION
**Pull request by rschristian**
The [WMR repo had a big release this morning](https://github.com/preactjs/wmr/releases) containing a few of the items I was waiting for, so I went and pushed this through. The main items were a `Route` component, which fixes some of the TS issues, and a fix to the `route()` method, as programmatic routing is used a fair bit here, and unfortunately that was broken.

Everything "works" though I think we need a Zustand release. They're swapping over to better support ESM, but until then, we end up with a huge `regenerator-runtime` and unshakeable `zustand/middleware`. Now `regenerator-runtime` is pure bloat, and makes up about 15% of our bundle. No good, but should just get deleted here next release. `zustand/middleware` is a good 5% that we use maybe 1% of. So we'll ditch another 4% which will be nice, but nothing major.

I also still need to work on code splitting. Not sure if it's just the visualizer I'm using (I've never used it before) or (more likely, IMO) I've done something wrong, but it seems like we're including everything by default. Just something to fix.

Good news is that, even with that Zustand junk and my non-working code splitting, the bundle is at 38kb w/ Brotli and 44kb w/ Gzip which certainly ain't bad! Especially with (hopefully) easy improvements on the horizon.

### CODE REVIEW

**Comment by rschristian** [comment]
Pretty much just waiting on https://github.com/pmndrs/zustand/pull/336

If it takes too long I'll toss up a quick fork of the package. Basically just missing ESM support for the state persistence. While we could write that ourselves, not really a good reason to when it (should) be just another import and 4 lines total.

**Comment by rschristian** [comment]
Should be good! Home page is now just 13kb, not including assets (CSS, fonts, etc.). Pretty light. 

I'd like to setup a custom asset pipeline to optimize those as they're horribly bloated at the moment. Not sure if I will, might go against the spirit of RealWorld anyhow.

**Comment by rschristian** [comment]
I'll rebase this onto #27

**Comment by rschristian** [comment]
I'll have to do a bit of reading on this, seems non-trivial to make a working jest setup due to the amount of "magic" WMR does.

**Comment by rschristian** [comment]
@mutoe Not really sure what to do about this PR. 

Getting Jest to work correctly seems to not be possible as `preact-iso` is an ESM-only package and Jest doesn't really support ESM at the moment. It can handle a few things but implodes at usage here with the HTM transform needed. Pre-compiling doesn't really help either.

I've played around with other test runners like [`uvu`](https://github.com/lukeed/uvu), however, the problem you run into there is that you cannot use any of the nice assertion extensions from `jest-dom` which, unlike the name might suggest, is made for `@testing-library`. So no `expect(...).toBeInTheDocument()` or `expect(...).toHaveAttribute()`, etc. I might toy with recreating this, but that will take time, and might not finish.

I'm thinking it's better to get WMR at cost of a test suite than to keep the test suite without WMR. WMR brings a lot of benefits to the bundle size, output, nicer dev experience, etc. We could cut the test suite out here but have another branch containing it as it is now. If we (or someone else) can get it working (might just have to wait for Jest / the Node loader API) then we can merge it back in. 

Curious for your thoughts, as I've been working with this for a few weeks on and off now, still can't get a (sane) combination to work. As such it seems we'd have to choose between test suite and WMR at the moment.

**Comment by mutoe** [comment]
@rschristian  There is the same issue when we using Vite. https://github.com/mutoe/vue3-realworld-example-app/blob/master/package.json

We have to use babel to transform the module to js file before running the test suite. Before there is a better solution, I think we can only retreat to the second best. I don't know if wmr is compatible with this approach.

**Comment by rschristian** [comment]
Don't think so.

I've definitely been using Babel heavily but don't think there's a winning combo due to the lack of support for Node native ESM from Jest and Node native packages in the toolchain. 

Then there's also the issue of the loader api (the thing that'll allow you to do transforms on a module that you import) not being finalized so everything has to be done AOT with Babel, can't be at runtime. That's more of an inconvenience though than a real problem, at least for the time being.

**Comment by rschristian** [comment]
I'm going to merge this in.

The test suite has been removed, but still exists on a branch & I've made a copy myself too. I'm certainly happy to be wrong, but I've spent _a long time_ working on permutations of babel plugins and the like to get valid JSX, TS, and ESM transforms and it doesn't seem possible at the moment. Don't think it's worth keeping WMR back for. 

Hopefully the loader API will stabalize and better ESM support from Jest et. al. will come out soon, making this switch super easy anyhow.

**Comment by mutoe** [comment]
Congratulations 🎉 🎉

**Pull request merged**
