### PR TITLE
Refactor/test suite

### PR DESCRIPTION
**Pull request by rschristian**
Pushing this just for tracking. 

I'm toying with `@testing-library/preact` and it certainly seems interesting. Seems like there's less work to do with the like the mocking and stuff you've set up for Enzyme (as Enzyme doesn't make that easy). Also caught a few accessibility concerns already, which is kinda cool. Testing-library is also supposed to be more resistant to changes, as it advocates against CSS selectors and the like, so maybe there's value there, though I can't say this has been proven to me yet. I haven't been using it for long enough to say either way.

Not sure yet if I even have the time to do this, just playing around right now. I think more and more people are moving to testing library, as can be seen with the last State of JS, so maybe it's worth is just for making this look "more modern". Not sure.

### CODE REVIEW

**Comment by mutoe** [comment]
I'm sure the Testing library is a better choice.

Compared with Enzyme, the Testing library is more inclined to integration testing. We don't need to care about the state changes inside preact. We only need to care about the value we input, click the button, and then the page changes.

It allows us to refactor with confidence. I have gained many benefits in the production code, and the a11y you mentioned is one of them. It also allows us to drive the code more naturally in TDD. I'm writing React, Vue and even Cypress use Testing library, it's so fragrant!

**Comment by rschristian** [comment]
Refactoring a test suite is miserable work. Note to self: don't do this again.

I've finally found the will/time to finish up the components, now just need to finish up the pages. The majority of the tests are still the same, just with `testing-library` instead of Enzyme. I've re-enabled the CI, and we're seeing quite good coverage on the the parts that are refactored at least. 

Hopefully will finish this up in the next few days.

**Comment by mutoe** [comment]
Seeing you have so many submissions, it's tough to work. Good job!

**Comment by rschristian** [comment]
The Article, EditArticle, Home, and part of the Profile page are not yet complete suites, and nothing exists for the API requests or store, but I'd say lets look at getting this in. I can add to the others/rewrite them later.

It'll allow for quick and safe edits to the parts that are covered by the suite right now, and I think that has quite a bit of benefit.

Sorry, this is a huge PR as-is.

**Pull request merged**
